#426
w3c/wcag-em-report-tool pull request #443
Opened 2021-05-17 11:56 UTC by mhansma96

Assertioncounter fix - the amount of open assertions now updates according to filters. Also the subcategories update with it

2021-05-17 14:49 UTC, hidde commented
Tested this in the preview, and I see an issue: changing the conformance target in step 2 does not affect totals, changing filter in step 4 does. This should be the other way around: changing target in step should impact the totals, checking/unchecking in step 4 should not.

Would you be able to check this? Thanks!

2021-05-17 18:24 UTC, mhansma96 commented
I see, I will look into it, but maybe do need a little bit of clarification. 
Since there are 2 sets of filters in this situation: the ones on step 2 and the ones on step 4. If the ones on step 2 filter the actual amount of assertions, what do the filters in step 4 add? Because using them also changes the amount of actual assertions on the screen.

2021-05-17 18:30 UTC, hidde commented
In step 2, the conformance target is the “goal“ of this report. It sets set a scope, so if the user says “I will report on WCAG 2.1 A + AA” in step 2, there are 50 SCs that fall under that, so their total will always be 50.

If they get to step 4, they can choose to look only at Level A or Level AA, but their goal is still A + AA (so the report will still show A + AA). 

Hope that helps.

2021-05-19 10:04 UTC, hidde requested changes
Ziet er allemaal goed uit, dank! 

Zag nog een aantal console logs, die mogen er wmb uit.

2021-05-19 10:04 UTC, hidde commented on src/components/ui/Auditor/Auditor.svelte
> +    console.log($scopeStore['CONFORMANCE_TARGET']);
zelfde als hierboven, deze console logs mogen denk ik weg

2021-05-19 10:04 UTC, hidde commented on src/components/ui/YourReport.svelte
> +    console.log(CriteriaSelected);
zelfde als boven

2021-05-19 11:12 UTC, hidde approved these changes

2021-05-19 11:13 UTC, merged